rc_ticks = {
    "figure.figsize": (1.67475, 1.386),
    "text.usetex": False,
    "font.size": 7,
    "legend.fontsize":6,
    "legend.title_fontsize":8,
    "xtick.labelsize":6,
    "ytick.labelsize": 6,
    "axes.labelsize":7,
    "axes.titlesize":7,
    "lines.linewidth": 1,
    "axes.linewidth": 0.4,
    "lines.markersize": 3,
    "xtick.major.size": 2.5,
    "xtick.major.width": 0.5,
    "xtick.major.pad": 1,
    "xtick.minor.size": 1.5,
    "xtick.minor.width": 0.5,
    "xtick.minor.pad": 1,
    "ytick.major.size": 2.5,
    "ytick.major.width": 0.5,
    "ytick.major.pad": 1,
    "ytick.minor.size": 1.5,
    "ytick.minor.width": 0.5,
    "ytick.minor.pad": 1,
    "axes.labelpad": 1,
    "axes.titlepad": 1,
    "figure.dpi": 600,
}