@startuml
    !include classes.puml
    remove @unlinked


    Scenario *-- MyGlobalModel
    MyGlobalModel *-- MyFieldTemplate


    Scenario <- InternalSolver
    EntityType -* Scenario
    Scenario *-- MyEntityLocator
    Scenario *-- MyParameterPool
    MyParameterPool *-- ParameterTemplate

@enduml




