@startuml
    !include classes.puml
    remove @unlinked

    StateManager *- SimContainer
    StateManager *-- ScanContainer
    ScanContainer *- ScanSample
    SimContainer *- GlobalProblem
    GlobalProblem *-- MySolver
    Entity --* SimContainer
    InternalSolver -* Entity

@enduml




