@startuml
    !include ../puml_src/classes.puml
    remove @unlinked

    PostProcessor *- PostProcessComputation
    PostProcessor <.. ComputeSettings
    PostProcessComputation <|-- FenicsScalarFieldComputation
    PostProcessComputation <|- ScalarComputation

@enduml


