#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 11 12:04:37 2019

@author: lukas
"""

import pygmsh 
import meshio

geom = pygmsh.opencascade.Geometry(
          characteristic_length_min=0.05,
          characteristic_length_max=0.1
          )
        
#domain =  geom.add_box([-1,-1,-1],[2,2,2])
entities = []

o = geom.add_point([0,0,0])
p1 = geom.add_point([1,0,0])
p2 = geom.add_point([0,-1,0])
p3 = geom.add_point([-1,0,0])
p4 = geom.add_point([0,1,0])

p5 = geom.add_point([0,0,1])
p6 = geom.add_point([0,0,-1])

c12 = geom.add_circle_arc(p1,o,p2)
c23 = geom.add_circle_arc(p2,o,p3)
c34 = geom.add_circle_arc(p3,o,p4)
c41 = geom.add_circle_arc(p4,o,p1)


c15 = geom.add_circle_arc(p1,o,p5)
c25 = geom.add_circle_arc(p2,o,p5)

c35 = geom.add_circle_arc(p3,o,p5)




ll1 = geom.add_line_loop([c12,c15,c25])
ll2 = geom.add_line_loop([c23,c25,c35])

#geom.add_surface(ll1)
#geom.add_surface(ll2)

geom.add_compound_surface([geom.add_surface(ll1),geom.add_surface(ll2)])


#geom.boolean_difference([geom.boolean_union([domain,ball_1_t])],entities)
mesh = pygmsh.generate_mesh(geom)
#print(mesh)
meshio.write("test.xdmf", 
             meshio.Mesh(
                points=mesh.points, 
                cells={"triangle": mesh.cells["triangle"]},
                point_data=mesh.point_data,
                cell_data={"triangle":mesh.cell_data["triangle"]},
                field_data=mesh.field_data
                )
)
#meshio.write("test.xdmf",mesh)