@startuml

    !include ../puml_src/classes.puml
    remove @unlinked
    ScanDefinition *- ScannableParameter
    ScanContainer <.. ScanDefinition
    ScanContainer *- ScanSample
    StateManager *- ScanContainer
    ScanSample *- ScanType


@enduml