name: Test example script

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2
    - name: Add conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: | 
        conda env update --file ./fenics_explicit.yml --name base
        conda env config vars set LD_LIBRARY_PATH=~/anaconda3/envs/base/lib
    - name: install package
      run: pip install -e .
    - name: create result directory
      run: | 
        sudo mkdir /extra
        sudo mkdir /extra/runner
        sudo chmod -R a+rxw /extra
    - name: run spherical
      run: python ./thesis/unit_tests/spherical_test_problem/run.py
      continue-on-error: true
    - name: post process
      run: python ./thesis/unit_tests/spherical_test_problem/post_process.py
    - name: unit test
      run: python ./thesis/unit_tests/spherical_test_problem/test.py
    - name: run box_static
      run: python ./thesis/unit_tests/box_static_R_saturation/run.py
      continue-on-error: true
    - name: post process
      run: python ./thesis/unit_tests/box_static_R_saturation/post_process.py
    - name: unit test
      run: python ./thesis/unit_tests/box_static_R_saturation/test.py
      
