name: Test example script

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2
    - name: Add conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: | 
        conda env update --file ./fenics_explicit.yml --name base
        conda env config vars set LD_LIBRARY_PATH=~/anaconda3/envs/base/lib
        conda activate base
    - name: install package
      run: pip install -e .
    - name: create result directory
      run: | 
        sudo mkdir /extra
        sudo mkdir /extra/runner
        sudo chmod -R a+rxw /extra
    - name: run test
      run: python ./thesis/example_scripts/example_hendrik/run.py > /extra/runner/run.txt
    - name: post process
      if: ${{ always() }}
      run: python ./thesis/example_scripts/example_hendrik/post_process.py 2
    - name: plot
      if: ${{ always() }}
      run: python ./thesis/example_scripts/example_hendrik/plot.py
    - name: upload-extra
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: upload extra
        path: /extra/runner/*
    - name: upload-images
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: upload extra
        path: /extra/runner/images/
