name: Test example script

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2
    - name: Add conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: conda env update --file ./fenics_explicit.yml --name base
    - name: install package
      run: pip install -e .
    - name: create result directory
      run: | 
        sudo mkdir /extra
        sudo chmod -R a+rxw /extra
    - name: run test
      run: python ./thesis/example_scripts/example_hendrik/run.py
    - name: post process
      run: python ./thesis/example_scripts/example_hendrik/post_process.py 2
    - name: plot
      run: python ./thesis/example_scripts/example_hendrik/plot.py
    - name: upload-extra
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: upload extra
        path: /extra/runner/*
