name: Build and commit documentation

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2
    - name: Add conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: | 
        conda env update --file ./fenics_explicit.yml --name base
        conda env config vars set LD_LIBRARY_PATH=~/anaconda3/envs/base/lib
    - name: install package
      run: pip install -e .
    - name: make html
      run: |
        cd docs
        make html
