@startuml
    !include ../puml_src/classes.puml
    remove @unlinked

    ParameterSet *- ParameterCollection
    ParameterCollection *- Parameter
    Parameter <|-- PhysicalParameter
    Parameter <|-- MiscParameter

@enduml